### ISSUE TITLE
Publish release as 1.1.0

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#156]
After hearing from Joe Barnes that #150 was indeed a breaking change for users, we should make the next release **1.1.0** and not **1.0.7**.  Previous discussion on 1.0.7 is #152 

- [x] Increment version to 1.10, not 1.07 #158 
- [x] Update Stack deprecation docs #157 
- [x] Improvements to top-level docs #165 

Release notes
=============

- Add Scala.js support with #109, #131, #133
- Fix #121, changes default encoding in `XML.save` to UTF-8 in #122
- Fix #46 with new config for minimizing tags in `PrettyPrinter`, see #90
- Fix defect #72 `XMLEventReader` does not handle `&apos;` properly with #89
- Fix defect #44 with fifth-edition names [SI-9060](http://issues.scala-lang.org/browse/SI-9060) in #93
- Fix defect #115 `NodeBuffer.toString` with #117
- Fix defect #118 Scaladoc links in apidocs to Scala standard library with #119
- Fix performance issue #136 lock contention from `lazy val` in `MetaData.normalize`
- Revert `Utility.escape` implementation to use `Iterator` instead of `while` with #102
- Fixed defect #154 with `NodeSeq` serialization with #155
- Fixed defect #183 with `stripComments`

**Comment by godenji** [comment]
@ashawley got an ETA for the 1.1.0 release?

**Comment by ashawley** [comment]
@godenji No, not yet

**Comment by ashawley** [comment]
I wonder if we should jam in #155 at the last minute and add it to the release, since next release is a major version update?  Any comments?

**Comment by joescii** [comment]
@ashawley I would greatly like to see a 1.0.7 release which includes #155, but doesn't include the breaking change in #150. I'll gladly do the git branch voodoo and submit PRs. The reason is Lift needs `NodeSeq` to be serializable for some new features being added in 3.2, but Lift will be broken by #150. 

Normally the obvious thing to do is release 1.1.0 with #155 (or 1.1.1 if we need to be more conservative with this project), and have Lift 3.2 explicitly depend on 1.1.x. Unfortunately [sbt has a bug](https://github.com/sbt/sbt/issues/3405) where it will NOT use the scala-xml version specified the the project classpath, but whatever one the scala compiler wants. What this means is that anyone using Lift 3.2 with 1.1.x will have a broken development environment. The Lift 3.2 binary will expect 1.1.x, but sbt will only use 1.0.x which that particular scala compiler version required. Hence Lift will never successfully run in sbt for development. AFAIK, no one is working on the sbt bug nor is anyone actively looking to address the issue. Given that classpath issues are pretty gnarly and I'm unfamiliar with the sbt code base, I'll be pretty challenged to correct the issue with an acceptable PR.

But 1.0.7 with the serialization fix without #150 won't have this problem. Only a small subset of Lift users will enable the feature. Secondly, the feature is for production, not development, hence it doesn't _need_ to behave correctly in sbt. Furthermore, this Lift feature I'm referencing will certainly require some thorough documentation, which can include a caveat about the sbt classpath in case someone tries to use the feature within sbt itself.

**Comment by ashawley** [comment]
Thanks for these comments @joescii 

I made multiple attempts at the compiler/scaladoc dependency issue for scala-xml. My last one was scala/scala#5689.  Being "pretty challenged to correct the issue with an acceptable PR" was my personal flaw as well.

I'm happy to entertain your proposals.  It sounds like we're pretty hamstrung in making binary changes to the library, IIUC:  If we making breaking changes and still use a big version number to signal the breaking change, you're saying the compiler won't let the user actually use an incompatible scala-xml dependency in sbt?  The compiler rules in sbt, essentially?

**Comment by joescii** [comment]
The way you rephrased it is correct. So if you're using scalac 2.12.2 and it depends on scala-xml 1.0.5 (I _think_ that's the version anyway), but your project needs scala-xml 1.1.0, your code is going to get the 1.0.5 jar and blow up. The issue I opened against sbt shows it in close detail.

**Comment by joescii** [comment]
I don't wanna over impose on a project I've not been dedicating my own time to, but I suspect the sbt bug forces into maintaining a branch with zero compatibility changes until the bug can be fixed and released. What do you think?

**Comment by ashawley** [comment]
That's been my conclusion as well.  Module system in 2.11 was possibly a feature that never existed.  I'm sort of the confused police detective played by Chazz Palminteri in Usual Suspects.

**Comment by joescii** [comment]
Give me a few minutes to do some git fu, and I'll push a pair of branches to my fork for some review.

**Comment by joescii** [comment]
It turns out I already had such a branch locally: https://github.com/joescii/scala-xml/tree/revert-150 

That branch should be a good branch for your backwards-compatible maintenance branch. I wasn't thinking long enough when I thought we needed a second branch. `master` is fine as is if y'all want it to continue as the latest and greatest.

**Comment by ashawley** [comment]
Thanks @joescii for all your work on this.  I grabbed your branch.  I'm sure it will come in handy.

**Comment by godenji** [comment]
Looks like a release has unfortunately been put on hold by the Lift saga. Would be nice to benefit from the new Scala.js support -- think we'll have something ready before end of the year?

**Comment by ashawley** [comment]
@godenji I hope so!

**Comment by SethTisue** [comment]
anything I, or anyone else interested, can help with here...?

**Comment by ashawley** [comment]
Whether to include #165 in 1.1.0, and if so, get a review.

Otherwise, I think it's whether to give one more look at the artifacts for Scala.js and Java 9 before finally pushing the tag and cutting a release.

**Comment by SethTisue** [comment]
#165 is merged.

I suggest not worrying about JDK 9, it's not a blocker for release. We can always do 1.1.1 and beyond.

**Comment by SethTisue** [comment]
as for Scala.js, you can ask that someone on the Scala team take a quick look before releasing the artifacts that you stage.

also, I wouldn't worry about it too much. if we get it wrong again, Scala.js users will tell us and we can do 1.1.1.

in general, I think it's okay to be slightly reckless and not worry too much if there turns out to be something wrong with 1.1.0. there's lots of nice changes to get out there, and the way to get community feedback on whether something broke is to get a release out there.

**Comment by godenji** [comment]
> there's lots of nice changes to get out there

Scala xml support in the browser alone is release worthy, nevermind the myriad other fixes/enhancements :)

**Comment by ashawley** [comment]
I've pushed the button and tagged v1.1.0.  Let's see how this goes!

**Comment by SethTisue** [comment]
I've closed the staging repositories (orgscala-lang-1472, orgscala-lang-1473). shall I release them to Maven Central?

**Comment by SethTisue** [comment]
whoosh! fly, artifacts, fly!

(I did check that the Scala.js artifacts are nonempty.)

**Comment by SethTisue** [comment]
perhaps the release notes should say something about binary compatibility?

**Comment by ashawley** [comment]
Agree, it seems worth mentioning.

> This is a minor release, not a patch release.  This release is binary compatible with the previous release, 1.0.6, but the default character encoding to `XML.save` was changed to UTF-8 from ISO-8859-1 which is not a forward-compatible change.

Any suggestions?

**Comment by SethTisue** [comment]
👍

also, artifacts are on Maven Central now:

* http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13.0-M3/1.1.0/
* http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.0/
* http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.1.0/

**Comment by ashawley** [comment]
Thanks, Seth.  I'm seeing them.

I've updated the release notes about binary compatability.
