### ISSUE TITLE
Releasing 1.1.1

### ISSUE THREAD

**Issue by hosamaly** [scala/scala-xml#236]
It would be great if we could see a new patch release of Scala XML soon!
Some of the closed issues targeting 1.1.1 would fix an issue that I'm having nowadays, particularly PR #113.

**Comment by ashawley** [comment]
Hosam,

Thanks for letting us know.  I agree there could be a patch release.  We have enough changes that are worth publishing.  We could probably release as is, but there are some remaining items that I would like to see closed in the milestone:

- [ ] #178 Doc for \ is imprecise
- [ ] #227 Relicense under Apache 2.0
- [ ] #232 Doc minimizeEmpty param of scala.xml.PrettyPrinter

These are also in the milestone, but could be pushed off to the next version:

- #17  More secure parsing
  - #177 Set safe defaults for parser settings
- #57  Characters unnecessarily escaped by toString
- #110 Add ScalaCheck specs
- #167 Escape apostrophes by default

**Comment by hosamaly** [comment]
Thank you, @ashawley. This sounds sensible. Would you like to update the [1.1.1 milestone](https://github.com/scala/scala-xml/milestone/7) to reflect this?

**Comment by ashawley** [comment]
Sure can.  I've updated the issue labels to reflect this in the 1.1.1 milestone.
